---
title: "ML-module-2"
output: ioslides_presentation
---

## Mean
Mean <br />
The mean value is the average value. <br />

To calculate the mean, find the sum of all values, and divide the sum by the number of values: <br />
(99+86+87+88+111+86+103+87+94+78+77+85+86) / 13 = 89.77 <br />
 
The NumPy module has a method for this.<br />
Example <br />
Use the NumPy mean() method to find the average speed: <br />
import numpy <br />
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86] <br />
x = numpy.mean(speed) <br />
print(x) <br />

## Mean, Median, and Mode
Mean, Median, and Mode <br />
In Machine Learning (and in mathematics) there are often three values that interests us: <br />

Mean - The average value <br />
Median - The mid point value <br />
Mode - The most common value <br />

Example: We have registered the speed of 13 cars: <br />

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86] <br />

What is the average, the middle, or the most common speed value?


## Median
Median <br />
The median value is the value in the middle, after you have sorted all the values: <br />
77, 78, 85, 86, 86, 86, 87, 87, 88, 94, 99, 103, 111 <br />

The NumPy module has a method for this: <br />

Example <br />
Use the NumPy median() method to find the middle value: <br />
import numpy <br />
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86] <br />
x = numpy.median(speed) <br />
print(x)

## Mode
Mode <br />
The Mode value is the value that appears the most number of times: <br />
99, 86, 87, 88, 111, 86, 103, 87, 94, 78, 77, 85, 86 = 86 <br />

The SciPy module has a method for this. <br />

Example <br />
Use the SciPy mode() method to find the number that appears the most:<br/>
from scipy import stats <br />
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86] <br />
x = stats.mode(speed) <br />
print(x)

## Conclusion