---
title: "python-module-4"
output: ioslides_presentation
---

## File Handling
File Handling <br />
The key function for working with files in Python is the open() function.
There are four different methods (modes) for opening a file:<br />
"r" - Read - Default value. Opens a file for reading, error if the file does not exist<br />
"a" - Append - Opens a file for appending, creates the file if it does not exist<br />
"w" - Write - Opens a file for writing, creates the file if it does not exist<br />
"x" - Create - Creates the specified file, returns an error if the file exists<br />

## Python File Open
Python File Open <br />
To open the file, use the built-in open() function.<br />

The open() function returns a file object, which has a read() method for reading the content of the file:<br />

Example<br />
f = open("demofile.txt", "r")<br />
print(f.read())

## Python File Write
Python File Write <br />
To write to an existing file, you must add a parameter to the open() function:<br />
"a" - Append - will append to the end of the file<br />
"w" - Write - will overwrite any existing content<br />
Example<br />
Open the file "demofile2.txt" and append content to the file:<br />
f = open("demofile2.txt", "a")<br />
f.write("Now the file has more content!")<br />
f.close()<br />
 #open and read the file after the appending:<br />
f = open("demofile2.txt", "r")<br />
print(f.read())

## Python Delete File
Python Delete File<br />
To delete a file, you must import the OS module, and run its os.remove() function: <br />

Example <br />
Remove the file "demofile.txt": <br />

import os <br />
os.remove("demofile.txt")

## Conclusion